# Simple Announce Packet Test
# Tests basic announce packet functionality

[metadata]
name = "Simple Announce Test"
description = "Basic test of announce packet creation and validation"
version = "1.0"
tags = ["announce", "basic"]
duration_seconds = 30
author = "BitChat Team"

[network]
[network.profile]
type = "Perfect"

[network.topology]
type = "FullyConnected"

[network.logging]
enable_packet_logging = true
enable_stats_logging = false
stats_interval_seconds = 10

[[peers]]
name = "alice"
[peers.behavior]
auto_discovery = true
auto_connect = true

[[peers]]
name = "bob"
[peers.behavior]
auto_discovery = true
auto_connect = true

# Simple test sequence
[[sequence]]
name = "test_connection"
at_time_seconds = 2.0
action = "SendMessage"
from = "alice"
to = "bob"
content = "Hello Bob!"

[[sequence]]
name = "test_response"
at_time_seconds = 4.0
action = "SendMessage"
from = "bob"
to = "alice"
content = "Hello Alice!"

[validation]
[[validation.final_checks]]
type = "PeerConnected"
peer1 = "alice"
peer2 = "bob"

[[validation.final_checks]]
type = "MessageCount"
peer = "alice"
expected_min = 1
expected_max = 1

[[validation.final_checks]]
type = "MessageCount"
peer = "bob"
expected_min = 1
expected_max = 1

[performance]
max_latency_ms = 100
max_packet_loss = 0.0
expected_throughput = 1.0